name: Testing

on:
  # push:
  #   branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_USER: test_user
      MONGO_PASSWORD: test_password
      DB_URI: mongodb://test_user:test_password@localhost:27017

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: '8.2.7'
          mongodb-username: ${{ env.MONGO_USER }}
          mongodb-password: ${{ env.MONGO_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
